# Use Debian-based Node image
FROM node:latest@sha256:159cdc1516d209c282294248073ab48d8b72c075ba421cb8cdf43baab1afe115

# Set working directory
WORKDIR /app

# Install necessary dependencies
RUN apt update && apt install -y curl sudo

# Install Helm
RUN curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

# Install Renovate globally
RUN npm install -g renovate

# Verify installations
RUN renovate --version && helm version

# Copy application files
COPY . .

# Keep container running
CMD ["tail", "-f", "/dev/null"]
