name: release
on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 10 * * *'
jobs:
  release:
    runs-on: ubuntu-22.04
    steps:

      - name: Check out repo
        uses: actions/checkout@master
      - name: Get version number
        run: |
          ls -la
          VERSION=$(cat version.yaml | grep 'version' | cut -d ' ' -f4)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Use version number in next step
        run: |
          echo $VERSION # use the version number here
      - name: replace version in Dockerfiel
        run: sed -i 's/VERSION/${{ env.VERSION }}/g' Dockerfile 
      - name: Login to Docker Hub
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@471d1dc4e07e5cdedd4c2171150001c434f0b7a4 # v6
        with:
          push: true
          tags: loeken/vaultwarden:1.33.1-alpine
          context: .
          no-cache: true
