name: release
on:
  push:
    branches: [ main ]
  schedule:
    - cron: '0 10 * * *'
jobs:
  release:
    runs-on: ubuntu-24.04
    steps:

      - name: Check out repo
        uses: actions/checkout@master
      - name: Login to Docker Hub
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@10e90e3645eae34f1e60eeb005ba3a3d33f178e8 # v6
        with:
          push: true
          tags: loeken/vaultwarden:1.34.1-alpine
          context: .
          no-cache: true
