name: Renovate

on:
  workflow_dispatch:  # Allows manual triggering of the workflow
  schedule:
    - cron: "0 3 * * *"  # Runs Renovate daily at 03:00 UTC

jobs:
  renovate:
    env:
      LOG_LEVEL: debug
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - name: Set up Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: 20  # Renovate requires Node.js 18+

      - name: Install Renovate
        run: npm install -g renovate

      - name: Run Renovate
        env:
          RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
          LOG_LEVEL: debug
        run: renovate loeken/docker-vaultwarden

